sudo: false
language: node_js
node_js:
 - "12.0.0"
env:
  global:
    CC_TEST_REPORTER_ID=775c7d830a0cc3d06e1cbf7fdac0e44dec76c095fc638557647751f51a06d3de
install:
  - npm install
before_script:
  - npm install codeclimate-test-reporter istanbul -g
script:
  - npm run coveralls
  - npm run coverage
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
notifications:
  email: false