const users = [
  {
    id: 1,
    email: 'admin@quickcredit.com',
    mobileno: '08082205956',
    firstName: 'Daniel',
    lastName: 'Ufeli',
    password: '$2a$10$Pei8CV/I0Z3BMFVJuJClaePYmvc.tKnaGK3xFXKJoTTjul84exLfe',
    address: '26, Fagbeyiro Street, Alakuko',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 2,
    email: 'user@quickcredit.com',
    mobileno: '08082205956',
    firstName: 'Daniel',
    lastName: 'Ufeli',
    password: '$2a$10$Pei8CV/I0Z3BMFVJuJClaePYmvc.tKnaGK3xFXKJoTTjul84exLfe',
    address: '26, Fagbeyiro Street, Alakuko',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 3,
    email: 'user1@quickcredit.com',
    mobileno: '08082205956',
    firstName: 'Daniel',
    lastName: 'Ufeli',
    password: '$2a$10$Pei8CV/I0Z3BMFVJuJClaePYmvc.tKnaGK3xFXKJoTTjul84exLfe',
    address: '26, Fagbeyiro Street, Alakuko',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 3,
    email: 'user2@quickcredit.com',
    mobileno: '08105334020',
    firstName: 'Daniel',
    lastName: 'Ufeli',
    password: '$2a$10$Pei8CV/I0Z3BMFVJuJClaePYmvc.tKnaGK3xFXKJoTTjul84exLfe',
    address: '26, Fagbeyiro Street, Alakuko',
    status: 'unverified',
    isAdmin: false,
  },
];

export default users;
